### ISSUE TITLE
Any plans for morty support?

### ISSUE THREAD

**Issue by agherzan** [emutex/meta-up-board#2]

**Comment by Dan-Lightsource** [comment]
@agherzan
Sorry for the delayed reply, Andrei.  Morty support is on my to-do list, but it will most likely be a few weeks more before I get near it.  How badly do you need it?

**Comment by agherzan** [comment]
Hi @Dan-Emutex . We are currently working in getting upboard supported by resin. Given that we switch most of our boards on morty it would have been nice to have upboard started on morty too. It's not a real problem but it would be nice.

**Comment by andrewlxer** [comment]
Any update on this?  Morty has been out for a while and up board support would be great.

**Comment by agherzan** [comment]
Hi @Dan-Emutex . Friendly ping on this one. Maybe we can start working on pyro now? The kernel patches seem to be upstreamed now in kernel tree which includes upboard2 support too.

**Comment by pricopb** [comment]
@agherzan 
Hi, Andrei!
I am currently working on pyro. I hope to have it released this week.
Thanks,
Bogdan

**Comment by agherzan** [comment]
What kernel version are you going to have that released based on? This is because I found a bug in yocto and you should probably be aware of it.

**Comment by nicola-lunghi** [comment]
Hi agherzan
please open a ticket here if its related to our yocto bsp layer
Regards
Nicola Lunghi

**Comment by agherzan** [comment]
The issue is based/dependent on the question. Is the pyro branch going to be on 4.9 kernel?

**Comment by pricopb** [comment]
@agherzan 
Thanks for the heads up Andrei!
The kernel is intel-linux 4.9 which seems to be based on Linux 4.9.30:
`
PREFERRED_PROVIDER_virtual/kernel ?= "linux-intel"
`
`
PREFERRED_VERSION_linux-intel ?= "4.9%"
`
Cheers,
Bogdan

**Comment by agherzan** [comment]
Be aware that the aufs on that version is broken. It includes a version incompatible with 4.9. I'm not sure how to fix this as this is coming from the yocto linux fork. In a nutshell the aufs sources still use getxattr while this was removed (https://patchwork.kernel.org/patch/9294421/).

**Comment by agherzan** [comment]
It looks like an old issue - most probably outdated. Closing for now.
